name: Docker file
on:
  push:
jobs:
  Docker_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Version
        run: docker --version

      - name: List of Containers
        run: docker ps

      - name: About Docker
        run: docker info
