name: Docker File
on:
  push:
    jobs:
      Docker_job:
        runs-on: ubuntu-latest

        steps:

          - name: Docker version
            run: docker --version

          - name: List of containers
            run: docker ps
              

