name: second-workflow

on:
  workflow_dispatch:

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello brother"

      - name: Bye
        run: echo "Bye Bye"
      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Check the workflow and responsed"
          body: "Workflows executed"
          to: ujjwala076121@gmail.com, sachintiwari74gpj@gmail.com
          from: ${{secrets.EMAIL_USERNAME}}
