name: second-workflow

on:
  push:

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello brother"

      - name: Bye
        run: echo "Bye Bye"

  new_job:
    needs: second_job
    runs-on: ubuntu-slim

    steps:
      - name: New Commands
        run: echo "Hello new commands"       
